FROM nginx:alpine

RUN mkdir -p /etc/ssl/certs/atc.turyelectro.com/
#COPY ./certbot/atc.turyelectro.com/fullchain.pem /etc/ssl/atc/fullchain.pem
#COPY ./certbot/atc.turyelectro.com/privkey.pem /etc/ssl/atc/privkey.pem
