FROM nginx:alpine

# Crea un usuario no privilegiado
#RUN useradd -ms /bin/bash usuario

# Cambia al usuario no privilegiado
#USER usuario

RUN mkdir -p /etc/ssl/alpine/
COPY ./certs/alpine-crm.key /etc/ssl/alpine/alpine-crm.key
COPY ./certs/alpine-crm.crt /etc/ssl/alpine/alpine-crm.crt

COPY ./certs/alpine-crm-1.key /etc/ssl/alpine/alpine-crm-1.key
COPY ./certs/alpine-crm-1.crt /etc/ssl/alpine/alpine-crm-1.crt

COPY ./certs/alpine-crm-2.key /etc/ssl/alpine/alpine-crm-2.key
COPY ./certs/alpine-crm-2.crt /etc/ssl/alpine/alpine-crm-2.crt

COPY ./certs/alpine-crm-3.key /etc/ssl/alpine/alpine-crm-3.key
COPY ./certs/alpine-crm-3.crt /etc/ssl/alpine/alpine-crm-3.crt

COPY ./certs/alpine-crm-4.key /etc/ssl/alpine/alpine-crm-4.key
COPY ./certs/alpine-crm-4.crt /etc/ssl/alpine/alpine-crm-4.crt

COPY ./certs/alpine-crm-5.key /etc/ssl/alpine/alpine-crm-5.key
COPY ./certs/alpine-crm-5.crt /etc/ssl/alpine/alpine-crm-5.crt

COPY ./certs/alpine-crm-6.key /etc/ssl/alpine/alpine-crm-6.key
COPY ./certs/alpine-crm-6.crt /etc/ssl/alpine/alpine-crm-6.crt

COPY ./certs/alpine-crm-7.key /etc/ssl/alpine/alpine-crm-7.key
COPY ./certs/alpine-crm-7.crt /etc/ssl/alpine/alpine-crm-7.crt

COPY ./certs/alpine-crm-8.key /etc/ssl/alpine/alpine-crm-8.key
COPY ./certs/alpine-crm-8.crt /etc/ssl/alpine/alpine-crm-8.crt

COPY ./certs/alpine-crm-9.key /etc/ssl/alpine/alpine-crm-9.key
COPY ./certs/alpine-crm-9.crt /etc/ssl/alpine/alpine-crm-9.crt

COPY ./certs/alpine-crm-10.key /etc/ssl/alpine/alpine-crm-10.key
COPY ./certs/alpine-crm-10.crt /etc/ssl/alpine/alpine-crm-10.crt